# Generated by Django 6.0.3 on 2026-03-17 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='replies',
            new_name='replies_count',
        ),
    ]
